# SonarQube project configuration
sonar.projectKey=psico-landing-page
sonar.projectName=Psico Landing Page
sonar.projectVersion=0.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=src/**/*.spec.ts,src/environments/**,src/main.ts
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.spec.ts,src/environments/**,src/main.ts
